### ISSUE TITLE
Local Sample-Server iOS / Integration Error

### ISSUE THREAD

**Issue by cesariel** [PayPal-Mobile/ios-here-sdk-dist#41]
If I have my sample-server in my computer, how can I configure the return URL from Paypal. Can you give me an example please?

I have:

exports.MY_HOSTNAME = "http://10.0.0.4";
exports.MY_PORT = 5000;
exports.MY_APP_URL = "http://x.x.x.x:5000//oauth";

Where x.x.x.x is the WAN IP given by (google "whats my ip").

But, when I run the server and the sample APP I keep getting the same Error:

Apparently logged into Heroku successfully - but we got a nil JSON dict

Error: (null)

Data: {"correlationId":"3ec9beb764936","errorCode":600031,"message":"Missing access token","developerMessage":"You must provide an access token when calling this API. It can be passed as either a header of the form \"Authorization: Bearer <access token>\" or as a query parameter called access_token.","errorType":"oauth/missing_access_token"}

I changed the STConstants.h to match the above too.

#define MID_TIER_SERVER_URL @"http://10.0.0.4:5000/sample-server"
#define LIST_OF_STAGES @[@"stage2md030", @"stage2mb024", @"stage2pph10", @"stage2pph03", @"stage2mb001", @"stage2mb006"]

Can you please help me?

Thanks!!

**Comment by ppmtscory** [comment]
When are you getting this error?  What are you doing when this occurs and what is showing in the console log for the request?

**Comment by ppmtscory** [comment]
Closing due to inactivity.  If you continue to have issues, please feel free to reopen with the answers to the above questions.

**Comment by cesariel** [comment]
Hi ppmtscory,

What I'm trying to do is to put the sample-server in Heroku, but when I'm deploying I received this error:

cesarielrp$ git push heroku master

Counting objects: 2071, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1926/1926), done.
Writing objects: 100% (2071/2071), 3.17 MiB | 223.00 KiB/s, done.
Total 2071 (delta 435), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Removing .DS_Store files
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  0.10.x
remote:        engines.npm (package.json):   2.13.x
remote:        
remote:        Resolving node version 0.10.x via semver.io...
remote:        Downloading and installing node 0.10.40...
remote:        Resolving npm version 2.13.x via semver.io...
remote:        Downloading and installing npm 2.13.5 (replacing version 1.4.28)...
remote: 
remote: -----> Restoring cache
remote:        Skipping cache (new runtime signature)
remote: 
remote: -----> Building dependencies
remote:        Prebuild detected (node_modules already exists)
remote:        Rebuilding any native modules
remote:        
remote:        > mdns@2.2.9 install /tmp/build_fc26e6f760e075a049004ec68afddd04/node_modules/mdns
remote:        > node-gyp rebuild
remote:        
remote:        make: Entering directory `/tmp/build_fc26e6f760e075a049004ec68afddd04/node_modules/mdns/build'
remote:          CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
remote:        In file included from ../src/dns_sd.cpp:1:0:
remote:        ../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
remote:         #include <dns_sd.h>
remote:                            ^
remote:        compilation terminated.
remote:        make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
remote:        make: Leaving directory `/tmp/build_fc26e6f760e075a049004ec68afddd04/node_modules/mdns/build'
remote:        gyp ERR! build error 
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_fc26e6f760e075a049004ec68afddd04/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
remote:        gyp ERR! System Linux 3.13.0-57-generic
remote:        gyp ERR! command "node" "/tmp/build_fc26e6f760e075a049004ec68afddd04/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_fc26e6f760e075a049004ec68afddd04/node_modules/mdns
remote:        gyp ERR! node -v v0.10.40
remote:        gyp ERR! node-gyp -v v2.0.2
remote:        gyp ERR! not ok 
remote:        
remote:        npm ERR! Linux 3.13.0-57-generic
remote:        npm ERR! argv "node" "/tmp/build_fc26e6f760e075a049004ec68afddd04/.heroku/node/bin/npm" "rebuild"
remote:        npm ERR! node v0.10.40
remote:        npm ERR! npm  v2.13.5
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! mdns@2.2.9 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR! 
remote:        npm ERR! Failed at the mdns@2.2.9 install script 'node-gyp rebuild'.
remote:        npm ERR! This is most likely a problem with the mdns package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     node-gyp rebuild
remote:        npm ERR! You can get their info via:
remote:        npm ERR!     npm owner ls mdns
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_fc26e6f760e075a049004ec68afddd04/npm-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        Some possible problems:
remote:        
remote:        - node_modules checked into source control
remote:          https://www.npmjs.org/doc/misc/npm-faq.html#should-i-check-my-node_modules-folder-into-git-
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote: 
remote:  !     Push rejected, failed to compile Node.js app
remote: 
remote: Verifying deploy....
remote: 
remote: !	Push rejected to amwaybm.
remote: 
To https://git.heroku.com/amwaybm.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/amwaybm.git'

**Comment by ppmtscory** [comment]
Will work this through issue #45

**Comment by cesariel** [comment]
Perfect!
